import type { Metadata } from "next";
import "../globals.css";
import { ReactNode } from "react";
import dynamic from "next/dynamic";

const ReduxProvider = dynamic(
  () => import("@/components/Provider/ReduxProvider"),
  {
    ssr: false,
    loading: () => (
      <div style={{ textAlign: "center", padding: "1rem" }}>
        <div className="spinner" />
      </div>
    ),
  }
);

export const metadata: Metadata = {
  title: "Rehabco Admin",
  description: "Generated by create next app",
  icons: {
    icon: "images/logo.svg",
  },
};
export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params?: { lang?: "en" | "ar" };
}) {
  return (
    <html lang={params?.lang} dir={params?.lang === "ar" ? "rtl" : "ltr"}>
      <head>
        <link rel="shortcut icon" href="/images/logo.svg" />
        <link rel="apple-touch-icon" href="/images/logo.svg" />
        <link rel="mask-icon" href="/images/logo.svg" />
      </head>
      <body>
        <ReduxProvider>
          <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  );
}
